### ISSUE TITLE
Doesn't seem to work on heroku

### ISSUE THREAD

**Issue by christianv** [dotcypress/koa-force-ssl#2]
@dotcypress do you have an example on how we can use this on heroku?

**Comment by turboMaCk** [comment]
+1

**Comment by turboMaCk** [comment]
@christianv This middleware can not work with Heroku. You can try this: https://github.com/turboMaCk/koa-sslify

**Comment by christianv** [comment]
@turboMaCk I'll definitely try that out, thanks!

**Comment by turboMaCk** [comment]
@christianv BTW... do not forget to use it only in production ENV if you do not have reverse proxy with ssl on your dev machine;) using NODE_ENV works fine in my case.

**Comment by turboMaCk** [comment]
@dotcypress added you to credits in: https://github.com/turboMaCk/koa-sslify
